version: '3.7'
services: 
    api:
        build:
            context: ./
            dockerfile: ./20MinuteBackend.API/Dockerfile
        ports: 
            - "80:80"
            - "443:443"
        environment: 
            - ConnectionStrings__BackendContext=Server=sql;Database=Backend;User Id=sa;Password=123123123Aa;
            - BaseUrl=https://localhost/
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123
            - ASPNETCORE_URLS=https://+:443;http://+:80
        volumes:
            - ~/.aspnet/https:/https:ro
        depends_on: 
            - sql
    cleaner:
        build:
            context: ./
            dockerfile: ./20MinuteBackend.Cleaner/Dockerfile
        environment: 
            - ConnectionStrings__BackendContext=Server=sql;Database=Backend;User Id=sa;Password=123123123Aa;
        depends_on: 
            - sql
    sql:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        ports: 
            - "1433:1433"
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=123123123Aa
            - MSSQL_PID=Express
